baseURL = 'https://rivermao.com/'
languageCode = 'en-us'
title = 'RiverMao'
theme = 'ivy'
publishDir = "docs"
hasCJKLanguage = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[menu]
[[menu.main]]
name = "rss"
url = "/index.xml"
weight = "100"
[[menu.main]]
name = "program"
url = "/program/"
weight = "1"
[[menu.main]]
name = "life"
url = "/life/"
weight = "2"
[[menu.main]]
identifier = "about"
name = "about"
url = "/about"
weight = "3"

[params]
# description abou this website
description = "环游是无趣~"
email = "Email:i@rivermao.com"
footer = "&copy; [RiverMao](https://rivermao.com) | since 2020 | *本站文章均为原创,转载请标明出处*"
[markup]
[goldmark]
[renderer]
unsafe = true
[highlight]
codeFences = false

